version: '3.9'

services:
  sqlserver:
    image: northwind-sqlserver
    build: .
    container_name: northwind_sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
