services:
  sqlserver:
    build:
      context: .
      args:
        SA_PASSWORD: ${SA_PASSWORD}
    image: northwind-sqlserver
    container_name: northwind_sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    command: /bin/bash /usr/src/app/entrypoint.sh
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql-data:
