version: '3.8'

services:
  sqlserver:
    build:
      context: .
      args:
        SA_PASSWORD: ${SA_PASSWORD}
    image: northwind-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
